import logging
import json
from typing import Dict, Any

from llm.provider import llm

logger = logging.getLogger(__name__)

SQL_REFINER_SYSTEM = """You are an expert BigQuery SQL engineer.
You are given a base SQL query that was generated by a rigid template engine, and the user's original natural language request.
Your job is to safely modify the base SQL query to fulfill any specific constraints the user asked for that the template engine couldn't handle.
Specifically, look for instructions like:
- "Top 3" -> Add `ORDER BY ... DESC LIMIT 3`
- "Lowest PE" -> Add `ORDER BY ... ASC LIMIT x`
- "Sort by..." -> Add `ORDER BY ...`

Rules:
1. ONLY modify the final `SELECT` statement (add ORDER BY, LIMIT, or tweak WHERE).
2. DO NOT change the inner CTEs or the JOIN logic unless absolutely necessary.
3. Make sure the column you order by actually exists in the `SELECT` projection!
4. Return ONLY a JSON object containing the refined SQL query. No markdown, no explanations.

Expected JSON format:
{"refined_sql": "SELECT ..."}
"""

class RefinerAgent:
    async def refine_query(self, user_query: str, base_sql: str) -> str:
        """
        Takes the base SQL and the user's query and asks the LLM to refine it (add ORDER BY, LIMIT, etc).
        """
        messages = [
            {"role": "system", "content": SQL_REFINER_SYSTEM},
            {"role": "user", "content": f"User Query: {user_query}\n\nBase SQL Query:\n{base_sql}\n\nRefine the Base SQL Query to perfectly match the User Query."}
        ]
        
        try:
            logger.info("Refining base SQL query...")
            response = await llm.generate_json(messages, temperature=0.1)
            refined_sql = response.get("refined_sql", base_sql)
            
            # Clean up newlines for cleaner JSON/logging
            refined_sql = " ".join(refined_sql.split())
            return refined_sql
        except Exception as e:
            logger.error(f"SQL Refiner failed: {e}")
            return base_sql

refiner_agent = RefinerAgent()
